version: "3"
services:
  lotus:
    build:
      context: .
      args:
        - URL=$NX_SERVER_URL
        - PORT=$NX_SERVER_PORT
    restart: always
    environment:
      - NX_SERVER_PORT=$NX_SERVER_PORT
      - NX_NX_TIMER=$NX_TIMER
    ports:
      - $NX_SERVER_PORT:$NX_SERVER_PORT
    container_name: lotus
